apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config # Base name
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: backend
data:
  # Database Configuration (placeholders, will be overridden by environment overlay)
  DB_HOST: "db-host-placeholder"
  DB_PORT: "5432"
  DB_USER: "user-service-db-user-placeholder" # Often from a secret, but name could be here
  DB_NAME: "user_service_db_placeholder"
  DB_SSL_MODE: "disable" # Or "require", "verify-full"

  # Redis Configuration (placeholders)
  REDIS_HOST: "redis-host-placeholder"
  REDIS_PORT: "6379"
  # REDIS_PASSWORD: "" # If Redis has a password, this should come from a Secret

  # Keycloak Configuration (placeholders for service discovery or direct URLs)
  KEYCLOAK_AUTH_SERVER_URL: "http://keycloak-url-placeholder/auth" # e.g. http://dev-keycloak-main.keycloak-dev.svc.cluster.local/auth
  KEYCLOAK_REALM: "your-realm-placeholder"
  KEYCLOAK_CLIENT_ID: "user-service-client"
  # KEYCLOAK_CLIENT_SECRET: "" # This should come from a Secret

  # Other application-specific configurations
  LOG_LEVEL: "info"
  SERVICE_PORT: "8080"
  # PRODUCT_SERVICE_URL: "http://product-service-url-placeholder" # If it calls product-service
