apiVersion: v1
kind: Service
metadata:
  name: user-service # Base name
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP # Default, suitable for internal services
  ports:
    - port: 80 # Port the service listens on
      targetPort: http # Matches the 'name' of the containerPort in Deployment
      protocol: TCP
      name: http
    # - port: 8081
    #   targetPort: metrics
    #   protocol: TCP
    #   name: metrics
  selector:
    app.kubernetes.io/name: user-service # Must match labels on the Pods
