apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../manifests/applications/backend/product-service/base/

namespace: product-service-dev

namePrefix: dev-

# commonLabels:
#   environment: development

images:
  - name: your-container-registry/product-service # Match base image name
    newTag: dev-latest

configMapGenerator:
  - name: product-service-config
    behavior: merge
    literals:
      - LOG_LEVEL="debug"
      - DB_HOST="dev-pg-main-pgbouncer.percona-dev.svc.cluster.local"
      - DB_USER="product_service_dev_db_user"
      - DB_NAME="product_service_dev_db"
      - REDIS_HOST="dev-redis-cache-master.redis-dev.svc.cluster.local"
      # - KEYCLOAK_AUTH_SERVER_URL="http://dev-keycloak-main.keycloak-dev.svc.cluster.local/auth" # If needed
      # - KEYCLOAK_REALM="development_realm"
      # - KEYCLOAK_CLIENT_ID="product-service-dev-client"
      - USER_SERVICE_URL="http://dev-user-service.user-service-dev.svc.cluster.local:80" # Internal service URL
    options:
      disableNameSuffixHash: true

patchesStrategicMerge:
  - patch-deployment-dev.yaml
