apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service # Match base name
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: product-service # Match container name
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-service-db-credentials-dev # Will be prefixed, e.g., dev-product-service-db-credentials
                  key: password
            # - name: REDIS_PASSWORD # If needed
            #   valueFrom:
            #     secretKeyRef:
            #       name: product-service-redis-credentials-dev
            #       key: password
            # - name: KEYCLOAK_CLIENT_SECRET # If needed
            #   valueFrom:
            #     secretKeyRef:
            #       name: product-service-keycloak-credentials-dev
            #       key: clientSecret
