# THIS FILE SHOULD BE ENCRYPTED WITH SOPS
# --- Secret for Product Service's own database user credentials ---
apiVersion: v1
kind: Secret
metadata:
  name: product-service-db-credentials # Kustomize will prefix with 'dev-'
  namespace: product-service-dev
type: Opaque
stringData:
  password: "replace_with_product_service_db_password_for_dev"

# --- (Optional) Secret for Product Service's Keycloak client credentials ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: product-service-keycloak-credentials # Kustomize will prefix
#   namespace: product-service-dev
# type: Opaque
# stringData:
#   clientSecret: "replace_with_keycloak_client_secret_for_product_service_dev"
