apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: <YOUR_GIT_REPOSITORY_URL> # Replace
    path: clusters/development/workloads/backend/product-service
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: product-service-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
