apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-frontend-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoj.io
spec:
  project: default

  source:
    repoURL: <YOUR_GIT_REPOSITORY_URL> # Replace
    path: clusters/development/workloads/frontend/react-app
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: react-frontend-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
