apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: <YOUR_GIT_REPOSITORY_URL> # Replace with your Git repository URL
    path: clusters/development/workloads/backend/user-service # Path to the Kustomize overlay
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: user-service-dev # Should match Kustomize overlay's namespace

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # retry:
    #   limit: 5
    #   backoff:
    #     duration: 5s
    #     factor: 2
    #     maxDuration: 3m
