apiVersion: v1
kind: Service
metadata:
  name: react-app # Base name
  labels:
    app.kubernetes.io/name: react-app
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http # Matches the 'name' of the containerPort in Deployment
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: react-app
