# THIS FILE SHOULD BE ENCRYPTED WITH SOPS: sops -e -i secrets.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials-dev # Must match what's in patch-db-config-dev.yaml
  namespace: keycloak-dev # Must match the Keycloak instance's namespace
type: Opaque
stringData:
  username: "keycloak_dev_user" # The user you will create in PostgreSQL
  password: "replace_with_strong_dev_password" # The password for that user
  # For Keycloak operator to pick up these values for its internal variables:
  # DB_DATABASE: "keycloak_dev_db" # This might be needed if operator sets KC_DB_DATABASE from here
  # DB_USERNAME: "keycloak_dev_user"
  # DB_PASSWORD: "replace_with_strong_dev_password"
  # KC_DB_USERNAME: "keycloak_dev_user" # Check Keycloak operator docs for exact env var names
  # KC_DB_PASSWORD: "replace_with_strong_dev_password"
