apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Inherit from the shared operator configurations
bases:
  - ../../../../manifests/shared/operators/ # Path to the shared operators kustomization

namespace: operators

# Example: If you needed to patch the Percona operator channel specifically for dev:
# patchesStrategicMerge:
#   - |-
#     apiVersion: operators.coreos.com/v1alpha1
#     kind: Subscription
#     metadata:
#       name: percona-postgresql-operator
#       namespace: operators # Must match
#     spec:
#       channel: "beta" # Override channel for dev

# commonLabels:
#   environment: development
#   cluster: dev-cluster
