apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: percona-postgresql-operator
  # The namespace where the operator will be installed.
  # This might be overridden or specified in the cluster-specific config.
  # For now, let's assume a common 'operators' namespace.
  namespace: operators
spec:
  channel: stable-v2.3
  installPlanApproval: Automatic
  name: percona-postgresql-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
