# clusters/development/workloads/backend/user-service/secrets.sops.yaml
# THIS FILE SHOULD BE ENCRYPTED WITH SOPS
# --- Secret for User Service's own database user credentials ---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-db-credentials # Kustomize will prefix this with 'dev-'
  namespace: user-service-dev # Will be patched by kustomization if ns is set there
type: Opaque
stringData:
  password: "replace_with_user_service_db_password_for_dev" # For user_service_dev_db_user

---
# --- Secret for User Service's Redis password (if Redis is password protected) ---
# This secret should contain the password for the 'dev-redis-cache' instance.
# Often the Redis operator creates a secret like 'dev-redis-cache-password'.
# This secret here would be if user-service needs that password.
# Alternatively, if Redis operator creates 'dev-redis-cache-secret' with 'redis-password' key:
# apiVersion: v1
# kind: Secret
# metadata:
#   name: user-service-redis-credentials # Kustomize will prefix
#   namespace: user-service-dev
# type: Opaque
# stringData:
#   password: "actual_redis_password_from_redis_operator_secret" # This value would be a lookup/copy

---
# --- Secret for User Service's Keycloak client credentials ---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-keycloak-credentials # Kustomize will prefix
  namespace: user-service-dev
type: Opaque
stringData:
  clientSecret: "replace_with_keycloak_client_secret_for_dev" # Secret for 'user-service-dev-client'
